.devcontainer/devcontainer.json
.dockerignore
Dockerfile
docker-compose.yml
package-lock.json
package.json
sql/create_db.sql/create_db.sql
sql/schema.sql/schema.sql
src/app.module.ts
src/main.ts
src/redis/redis.module.ts

백엔드 기초 설정입니다.
그냥 Docker로 실행하시고 DB 생성되는지 확인해보세요
----확인 방법----
1. DB에 연결할 수 있는 툴(DataGrip, DBEaver)에서 도커 DB에 연결해서 DB 및 테이블 상태 확인
2. clone 받은 디렉토리(backend)의 터미널에서 docker exec -it backend-postgres-1 psql -U pixel_user -d pick_px 입력했을 때 pick_px=#  이라고 나오고 \dt라고 했을때 테이블이 나오면 정상 작동한겁니다.
모두 화이팅 합시다

Backend basic config

---

.dockerignore
Dockerfile
docker-compose.yml
eslint.config.mjs
package-lock.json
package.json
sql/schema.sql/schema.sql
src/app.module.ts
src/canvas/canvas.controller.spec.ts
src/canvas/canvas.module.ts
src/canvas/canvas.service.spec.ts
src/canvas/canvas.service.ts
src/canvas/entity/canvas.entity.ts
src/data-source.ts
src/database/database.module.ts
src/main.ts
src/pixel/entity/pixel.entity.ts
src/pixel/pixel.service.spec.ts
src/pixel/pixel.service.ts
src/queues/bullmq.config.ts
src/queues/bullmq.queue.ts
src/queues/bullmq.redis.ts
src/queues/bullmq.worker.ts
src/redis/redis.module.ts

캔버스 생성 API 구현입니다. 캔버스 생성 후 백그라운드 Worker를 이용해서 캔버스 사이즈에 맞게 픽셀 데이터를 초기화해서 DB에 넣는 과정까지 구현되었습니다.
반박 환영

SCRUM-15: 캔버스 및 픽셀 데이터 생성 api

---

src/auth/auth.module.ts
src/auth/auth.service.ts
src/auth/jwt.guard.ts
src/auth/jwt.strategy.ts
src/main.ts
src/user/user.controller.ts
src/user/user.module.ts
src/user/user.service.ts

API 용으로 JWT 검증 기능 추가
사용법 모르겠으면 문의 바람

[SCRUM-24] API용 JWT 검증 완료

---

src/canvas/canvas.service.ts
src/group/group.gateway.ts

- 사용자가 로그인하면 소켓 연결을 끊고(disconnect) 다시 연결(connect)한다.
- 소켓 연결 시에는 **canvas_id 룸**에만 join한다(픽셀 실시간 수신용).
- 채팅 버튼을 누르면 **group_id(전체/그룹) 룸**에 join한다.
- 다른 그룹 채팅 버튼을 누르면,
기존 group_id 룸에서 leave 후 새 group_id 룸에 join한다.
- 항상 group_id 룸은 1개만 유지된다.
- 프론트에서 `leave_chat` 이벤트를 emit하여 현재 group_id 룸에서 leave한다.
- 소켓 연결은 유지(픽셀 실시간 기능 때문).
---
```
socket.emit('join_chat', { group_id: '123' });
```
- 서버가 기존 group_id 룸에서 leave 후, 새 group_id로 join
```
socket.emit('leave_chat', { group_id: '123' });
```
- 서버가 해당 group_id 룸에서 leave
```
socket.emit('join_canvas', { canvas_id: '456' });
```
- canvas_id 룸은 항상 유지
---
- `join_chat`에서 기존 group_id 룸을 leave하고, 새 group_id로 join하는 로직 추가
- `leave_chat` 이벤트 핸들러 추가(프론트에서 채팅창 닫을 때 호출)
- canvas_id 룸은 건드리지 않음
- Redis에 쌓인 채팅 메시지를 30초마다 DB로 flush
- 실시간 채팅에는 임시 ID(Date.now()) …

[SCRUM-81] chat 관련 로직 수정

---

src/auth/auth.controller.ts
src/user/user.controller.ts

[SCRUM-84] JWT hotfix

---

src/auth/auth.controller.ts
src/auth/auth.service.ts
src/interface/JwtPaylod.interface.ts
src/interface/SignedCookies.interface.ts
src/user/user.controller.ts
src/user/user.service.ts

[SCRUM-91] Logout API

---

sql/schema.sql/schema.sql
src/auth/auth.service.ts
src/canvas/canvas.controller.ts
src/canvas/canvas.gateway.ts
src/canvas/canvas.service.ts
src/entity/GroupUser.entity.ts
src/group/dto/group-id.dto.ts
src/group/group.controller.ts
src/group/group.gateway.ts
src/group/group.service.ts
src/main.ts
src/queues/bullmq.worker.ts

그룹 생성, 가입 시 제약 조건 추가 ( 캔버스 별 최대 가입 그룹 3개)

[SCRUM-92] group and refresh token bug fix 

---

sql/schema.sql/schema.sql
src/canvas/canvas.controller.ts
src/canvas/canvas.service.ts
src/canvas/entity/canvas.entity.ts
src/group/group.service.ts
src/interface/CanvasInfo.interface.ts

1. 운영 상태에 따라서 캔버스 목록 조회하는 API 구현
2. DB 제약조건 업데이트 -> docker compose down -v 필수
3. createCanvas시 GroupUser에 canvas_id 할당 안하던 버그 해결

[SCRUM-111] : Canvas list API

---

docker-compose.yml
src/app.gateway.ts
src/auth/jwt.strategy.ts
src/canvas/canvas.gateway.ts
src/canvas/canvas.service.ts
src/group/group.gateway.ts
src/group/group.module.ts
src/group/group.service.ts
src/queues/bullmq.worker.ts
src/redis/redis.module.ts

- **현재**: 1개 Redis로 통합 운영 (메모리 효율성)
- **설정**: 512MB 메모리로 픽셀/채팅/기본 용도 모두 처리
- **확장 준비**: 3개 Redis 분리 설정을 주석으로 보존하여 필요시 즉시 전환 가능
- **기존**: 단일 Redis로 모든 데이터 처리
- **개선**: 픽셀/채팅/기본 Redis 분리 (트래픽 증가시 활성화)
```yaml
redis:        # 기본 (6379) - 세션, 캐시
redis-pixel:  # 픽셀 전용 (6380) - 512MB
redis-chat:   # 채팅 전용 (6381) - 256MB
```
- **기존**: 개별 키-값 방식 (`canvas:1:0:0` → `#FF0000`)
- **개선**: Hash 구조로 메모리 효율성 향상
```redis
HSET canvas:1 "0:0" "#FF0000"
HSET canvas:1 "1:1" "#00FF00"
HSET canvas:1 "2:2" "#0000FF"
```
- **장점**: 
- 메모리 사용량 30% 절약
- 캔버스별 원자적 TTL 관리
- 조회 성능 향상 (HGETALL)
- **전체 통합 배치 큐**: 픽셀과 채팅을 하나의 워커에서 처리
- **중복 제거**: Set 사용으로 동일 픽셀의 최신값만 유지
- **배치 크기**: 픽셀 200개, 채팅 100개 단위로 DB 저장
- **이중 flush**: 배치 크기 도달 시 즉시 처리 + 10초마다 안전장치
- **이벤트 기반 처리**: Gateway에서 이벤트 발행, 워커에서 구독
- **실시간 처리**: 픽셀/채팅 변경사항을 …

[SCRUM-108] redis optimization

---

.github/workflows/deploy.yml

[Hotfix] : github action error fix

---

docker-compose.dev.yml

[SCRUM-124]  docker-compose.dev.yml change:

---

.github/workflows/deploy.yml
docker-compose.dev.yml

[FIx] docker-compose.dev change

---

.gitignore
sql/create_db/create_db.sql
sql/schema/schema.sql

DB 이름 변경 (pick_px -> nestjs_db)

[SCRUM-128] DB name change

---

k8s/ingress.yaml

[Test] ingress file changed

---

src/canvas/canvas.gateway.ts

[Hotfix] draw pixel event fix

---

package-lock.json
package.json
sql/schema/schema.sql
src/app.module.ts
src/auth/auth.controller.ts
src/auth/jwt.strategy.ts
src/aws/aws.module.ts
src/aws/aws.service.spec.ts
src/aws/aws.service.ts
src/canvas/canvas.controller.ts
src/canvas/dto/create_canvas_dto.dto.ts
src/group/dto/create_url.dto.ts
src/group/dto/overlay.dto.ts
src/group/entity/group.entity.ts
src/group/group.controller.ts
src/group/group.gateway.ts
src/group/group.module.ts
src/group/group.service.ts
src/main.ts
src/user/user.controller.ts

1. S3 연결 및 그룹 오버레이 저장을 위한 pre signed url 발급 API
2. upload_img, send_img로 오버레이 이미지 저장 완료 시 db에 반영 및 그룹원에게 broadcast
3. create canvas시 swagger에서 started_at, ended_at이 서버 빌드 시간과 빌드 시간 하루 뒤로 설정

[SCRUM-146] s3 connection

---

package-lock.json
package.json
src/app.gateway.ts
src/auth/auth.controller.ts
src/canvas/canvas.gateway.ts
src/group/group.gateway.ts
src/user/user.controller.ts

- Redis를 활용한 실시간 접속자 수 관리 시스템 신규 구축
- Socket.IO Redis Adapter 도입으로 멀티 서버 환경 지원
- JWT 기반 세션 관리 시스템 구축
---
```typescript
// 모든 Gateway에서 Socket.IO Redis Adapter 설정
const pubClient = redis;
const subClient = redis.duplicate();
server.adapter(createAdapter(pubClient, subClient));
```
- **목적**: 멀티 서버 환경에서 소켓 이벤트 동기화
- **효과**: 로드밸런서 환경에서도 실시간 통신 안정성 확보
```typescript
// 소켓 연결 수 기반 접속자 수 계산
await redis.sadd('active_sockets', socketId);
const activeSocketCount = await redis.scard('active_sockets');
```
- **신규 기능**: 소켓 연결 수 기반 접속자 수 카운팅
- **최적화**: 디바운싱과 중복 방지로 성능 향상
- **기능**: 전체 접속자 수 + 캔버스별 접속자 수 제공
```typescript
// JWT 검증 결과를 Redis에 저장
const sessionKey = `socket:${socketId}:user`;
const userKey = `user:${userId}:sockets`; // 멀티 디바이스 지원
await redis.set(sessionKey, JSON.stringify(user));
await …
```

[SCRUM-157] 멀티 서버 환경 지원을 위한 Socket.IO Redis Adapter 적용 및 실시간 접속자 수 관리 시스템 구현

---

sql/schema/schema.sql

[SCRUM-167] schema.sql fix

---

src/group/group.gateway.ts

[SCRUM-170] group overlay socket event change

---

src/group/group.service.ts

buckey -> bucket

---

sql/schema/schema.sql
src/app.module.ts
src/canvas/canvas.controller.ts
src/canvas/canvas.service.ts
src/game/dto/waitingResponse.dto.ts
src/game/entity/game_result.entity.ts
src/game/entity/question_user.entity.ts
src/game/game.controller.spec.ts
src/game/game.controller.ts
src/game/game.module.ts
src/game/game.service.spec.ts
src/game/game.service.ts
src/group/group.service.ts
src/util/colorGenerator.util.ts

대기실 입장 시 컬러 배정 및 문제 발송 API
- 색상 랜덤 배정
- DB에 있는 전체 문제 유저마다 랜덤한 순서로 전송
- GameUserResult, QuestionUser 등 게임을 위한 데이터 입력

[SCRUM-194] color assign

---

src/game/dto/waitingResponse.dto.ts
src/game/game.controller.ts
src/game/game.service.ts

[SCRUM-202] waitingroom bugfix

---

.github/workflows/deploy.yml
src/queues/bullmq.worker.ts
src/queues/history.worker.ts

[Hotfix] worker path error

---

src/game/dto/uploadQuestion.dto.ts
src/game/game.controller.ts
src/game/game.service.ts

[SCRUM-235] question limit 100
